---
title: "Brain Visual"
author: "Rohan Dalmia"
date: "12/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read Data

```{r}
inf_own_pos = read.csv("112_infant_2_AALROImeanTimeCoursesInfOwnPos.csv")
```

## Install Packages

```{r, eval=FALSE}
install.packages("igraph")
install.packages("brainGraph")
```

## Data prep
```{r}
library(brainGraph)
cor_mat_infpos = as.matrix(inf_own_pos)
cor_mat2 = cor_mat_infpos[,-1]
rownames(cor_mat2) = cor_mat2[,1]
data = cor_mat2

part_name = c('Precentral_L', 'Precentral_R', 'Frontal_Sup_L',
                'Frontal_Sup_R', 'Frontal_Sup_Orb_L', 'Frontal_Sup_Orb_R',
                'Frontal_Mid_L', 'Frontal_Mid_R', 'Frontal_Mid_Orb_L',
                'Frontal_Mid_Orb_R', 'Frontal_Inf_Oper_L', 'Frontal_Inf_Oper_R',
                'Frontal_Inf_Tri_L', 'Frontal_Inf_Tri_R', 'Frontal_Inf_Orb_L',
                'Frontal_Inf_Orb_R', 'Rolandic_Oper_L', 'Rolandic_Oper_R',
                'Supp_Motor_Area_L', 'Supp_Motor_Area_R', 'Olfactory_L',
                'Olfactory_R', 'Frontal_Sup_Medial_L', 'Frontal_Sup_Medial_R',
                'Frontal_Med_Orb_L', 'Frontal_Med_Orb_R', 'Rectus_L', 'Rectus_R',
                'Insula_L', 'Insula_R', 'Cingulum_Ant_L', 'Cingulum_Ant_R',
                'Cingulum_Mid_L', 'Cingulum_Mid_R', 'Cingulum_Post_L',
                'Cingulum_Post_R', 'Hippocampus_L', 'Hippocampus_R',
                'ParaHippocampal_L', 'ParaHippocampal_R', 'Amygdala_L',
                'Amygdala_R', 'Calcarine_L', 'Calcarine_R', 'Cuneus_L',
                'Cuneus_R', 'Lingual_L', 'Lingual_R', 'Occipital_Sup_L',
                'Occipital_Sup_R', 'Occipital_Mid_L', 'Occipital_Mid_R',
                'Occipital_Inf_L', 'Occipital_Inf_R', 'Fusiform_L', 'Fusiform_R',
                'Postcentral_L', 'Postcentral_R', 'Parietal_Sup_L', 'Parietal_Sup_R',
                'Parietal_Inf_L', 'Parietal_Inf_R', 'SupraMarginal_L', 
                'SupraMarginal_R', 'Angular_L', 'Angular_R', 'Precuneus_L',
                'Precuneus_R', 'Paracentral_Lobule_L', 'Paracentral_Lobule_R',
                'Caudate_L', 'Caudate_R', 'Putamen_L', 'Putamen_R', 'Pallidum_L',
                'Pallidum_R', 'Thalamus_L', 'Thalamus_R', 'Heschl_L', 'Heschl_R',
                'Temporal_Sup_L', 'Temporal_Sup_R', 'Temporal_Pole_Sup_L',
                'Temporal_Pole_Sup_R', 'Temporal_Mid_L', 'Temporal_Mid_R',
                'Temporal_Pole_Mid_L', 'Temporal_Pole_Mid_R', 'Temporal_Inf_L',
                'Temporal_Inf_R', 'Cerebelum_Crus1_L', 'Cerebelum_Crus1_R',
                'Cerebelum_Crus2_L', 'Cerebelum_Crus2_R', 'Cerebelum_3_L',
                'Cerebelum_3_R', 'Cerebelum_4_5_L', 'Cerebelum_4_5_R',
                'Cerebelum_6_L', 'Cerebelum_6_R', 'Cerebelum_7b_L',
                'Cerebelum_7b_R', 'Cerebelum_8_L', 'Cerebelum_8_R',
                'Cerebelum_9_L', 'Cerebelum_9_R', 'Cerebelum_10_L',
                'Cerebelum_10_R', 'Vermis_1_2', 'Vermis_3', 'Vermis_4_5',
                'Vermis_6', 'Vermis_7', 'Vermis_8', 'Vermis_9', 'Vermis_10')

part_code = aal116$name
fin = data.frame(Name = part_name, Code = part_code)
fin$Code = levels(fin$Code)[as.numeric(fin$Code)]
fin$Name = levels(fin$Name)[as.numeric(fin$Name)]
for (j in 1:116) {
for (i in 1:116) {
  if(colnames(data)[j] == fin$Name[i])
    colnames(data)[j] = fin$Code[i]
  }
}

rownames(data) = colnames(data)
```

## Creating Network

```{r}
library(igraph)
library(tidyverse)
library(dplyr)
cor_g <- graph_from_adjacency_matrix(data, mode='directed',
                                     weighted = 'correlation')
cor_edge_list <- igraph::as_data_frame(cor_g, 'edges')
only_sig <- cor_edge_list[abs(cor_edge_list$correlation)>.93 &
                            abs(cor_edge_list$correlation)<1 , ]
new_g <- graph_from_data_frame(only_sig, T)

```

## Creating Brain Plot

```{r message=TRUE, warning=TRUE}
x = make_brainGraph(new_g, atlas = "aal116") #brain graph object
t = rich_club_coeff(x)$phi
plot(x, plane='sagittal', hemi='R',
     vertex.label=NA, vertex.size=10, vertex.color='color.lobe',
     edge.color='color.lobe', edge.width=10, show.legend = F,
     main = 'Right Hemisphere')
plot(x, plane='sagittal', hemi='L',
     vertex.label=NA, vertex.size=10, vertex.color='color.lobe',
     edge.color='color.lobe', edge.width=20, show.legend = F,
     main = 'Left Hemisphere')
plot(x, vertex.label=NA, plane='axial', vertex.color='color.lobe',
     edge.color='color.lobe', main = "Inf Own Pos", show.legend = T,
     vertex.size = 5, cex.main = 2)

```

